### ISSUE TITLE
Architecture v0.2

### ISSUE THREAD

**Issue by nrbnlulu** [nrbnlulu/qtgql#88]
# Workflow
![image](https://user-images.githubusercontent.com/88795475/219346165-e4f1ded3-d56a-4bbe-9cef-18702e0870af.png)# 

# Reference
## Types - `QGraphQLObject`
Each GraphQL type mirrors a `QGraphQLObject` with corresponding properties as field.

- [x] All properties are null-able since you can query for only so and so fields.
- [x] Every type instance is unique both server-client side
- [x] Deserializers for fields (nullable)
## `.graphql` files
use should provide two .graphql files, one for the schema definition (`schema.graphql`) 
and one for all the operations that would used on the app.(`operations.graphql`)

## `NetworkProto`
a protocol that accepts `HandlerProto` and expected to call the relevant hooks
when data/error/completed arrive.
default implementation is with the builtin `GqlWsTransportClient`. implemented in #101 

## Environment
encapsulates schema integration.

## `BaseQueryHandler` -  initial implementation in #89 
A `QObject` singleton with the following properties:
Should be imported and used as a singleton.
Codgen will create handlers for each query it finds.
Each handler is identified by the query `operationName`.

- [x] `property QObject data: QtObject` the root object of a successful query.
- [x] `property bool completed: false` whether the operation is on the fly (what about subscriptions? currently treated as queries)  
- [ ] `errors` - TBD - tracked by #140
- [x] support updates. - implemented in #112 

#### slots
- [x] `refetch()` refetches the query? #142 

## `UseQuery{}`
A `QQuickItem` (for convenience):
`property string operationName`

Allows to declare a dependency on an operation (QueryHandler), setting the operation name would
result in addition to consumers count on the operation (and fetching if it isn't already been fetched.).
implemented in #104 

### Updates
- [x] #105
- [x] when a query result is returned it is deserialized by the deserializers chain (starting from root query) if an id was found in store it gets validated if we need to update a field the setter is called thus emmits the signal, otherwise it instantiate a new object. if it was a list, we iterate thru the list and append / modify correspondingly. implemented in #112 
### Garbage collection
- [x] #134
- [x]  when component that had data  before and it was deleted, refetch the data. (edge case would be nullable root fields.) #142 

## Server-side assumptions
[Relay-spec](https://relay.dev/docs/guides/graphql-server-specification/) compatible server.
